import { get, save, transaction } from '../db/index.js';
import { generate } from './generator.js';
import { validateVersion } from './validation.js';
import { clone, now, uuid } from './utils.js';
export async function generateProposal(rosterId, deps, options = {}) { const roster = await get('rosters', rosterId); const prior = roster.draftVersionId ? await get('rosterVersions', roster.draftVersionId) : null; const version = generate(roster, prior, deps.rules, deps.employees, deps.availabilities, { resetGenerated: true, ...options }); await transaction(async tx => { await tx.objectStore('rosterVersions').put(version); roster.draftVersionId = version.id; roster.updatedAt = now(); await tx.objectStore('rosters').put(roster); }); return version; }
export async function acceptProposal(versionId, deps) { const version = await get('rosterVersions', versionId), roster = await get('rosters', version.rosterId); if (!version || version.status !== 'proposal') throw new Error('Only a proposal can be accepted.'); version.coverageReport = validateVersion(version, deps.employees, deps.availabilities); await transaction(async tx => { if (roster.productiveVersionId) { const old = await tx.objectStore('rosterVersions').get(roster.productiveVersionId); old.status = 'archived'; old.updatedAt = now(); await tx.objectStore('rosterVersions').put(old); } version.status = 'productive'; version.acceptedAt = now(); version.updatedAt = now(); roster.productiveVersionId = version.id; roster.draftVersionId = undefined; roster.updatedAt = now(); await tx.objectStore('rosterVersions').put(version); await tx.objectStore('rosters').put(roster); }); return version; }
export async function copyProductiveToProposal(rosterId) { const roster = await get('rosters', rosterId), productive = await get('rosterVersions', roster.productiveVersionId); if (!productive) throw new Error('There is no productive version to copy.'); const proposal = clone(productive); proposal.id = uuid(); proposal.status = 'proposal'; proposal.createdAt = proposal.updatedAt = now(); delete proposal.acceptedAt; await transaction(async tx => { roster.draftVersionId = proposal.id; await tx.objectStore('rosterVersions').put(proposal); await tx.objectStore('rosters').put(roster); }); return proposal; }
export async function regenerateProposalFrom(rosterId, fromDate, deps, options = {}) { return generateProposal(rosterId, deps, { ...options, fromDate }); }
export async function editProposalAssignment(versionId, change, deps) { const version = await get('rosterVersions', versionId); if (!version || version.status !== 'proposal') throw new Error('Productive rosters are read-only.'); const shift = version.shifts.find(s => s.id === change.shiftId); if (!shift) throw new Error('Shift not found.'); if (change.type === 'remove') shift.assignments = shift.assignments.filter(a => a.id !== change.assignmentId);
  else { if (shift.assignments.length >= shift.maxStaff) throw new Error('Maximum staffing reached.'); const other = version.shifts.find(s => s.date === shift.date && s.assignments.some(a => a.employeeId === change.employeeId)); if (other) throw new Error('An employee may work only one shift per day.'); shift.assignments.push({ id: uuid(), employeeId: change.employeeId, source: 'manual', locked: true, note: change.note, createdAt: now(), updatedAt: now() }); }
  version.coverageReport = validateVersion(version, deps.employees, deps.availabilities); version.updatedAt = now(); await save('rosterVersions', version); return version; }
export async function setAssignmentLock(versionId, assignmentId, locked) { const version = await get('rosterVersions', versionId); if (!version || version.status !== 'proposal') throw new Error('Productive rosters are read-only.'); const assignment = version.shifts.flatMap(s => s.assignments).find(a => a.id === assignmentId); if (!assignment) throw new Error('Assignment not found.'); assignment.locked = locked; if (locked) assignment.source = 'manual'; assignment.updatedAt = now(); await save('rosterVersions', version); return version; }
export async function addManualShift(versionId, date, rule, deps) { const version = await get('rosterVersions', versionId); if (!version || version.status !== 'proposal') throw new Error('Productive rosters are read-only.'); if (!rule) throw new Error('Choose a shift template.'); const shift = { id: uuid(), date, ruleId: rule.id, name: rule.name, locationId: rule.locationId, minStaff: rule.minStaff, maxStaff: rule.maxStaff, assignments: [], manual: true }; version.shifts.push(shift); version.coverageReport = validateVersion(version, deps.employees, deps.availabilities); version.updatedAt = now(); await save('rosterVersions', version); return version; }
