import './style.css';
import { registerSW } from 'virtual:pwa-register';
import * as db from './db/index.js';
import { create, get, list, save, remove, exportBackup, replaceBackup } from './db/index.js';
import { makeImportPreview, entriesForImport } from './core/availability.js';
import { generateProposal, regenerateProposalFrom, acceptProposal, copyProductiveToProposal, editProposalAssignment, setAssignmentLock } from './core/versions.js';
import { monthDates, uuid } from './core/utils.js';
const app = document.querySelector('#app'); let toast = ''; let preview;
const channel = new BroadcastChannel('roster-planner'); channel.onmessage = () => { toast = 'Data changed in another tab. View refreshed.'; render(); };
registerSW({ onNeedRefresh() { toast = 'A new version is available. Reload the page to update.'; render(); } });
const deps = async () => ({ employees: await list('employees'), availabilities: await list('availabilities'), rules: await list('shiftRules') });
const notice = (text) => `<p class="notice">${text}</p>`;
const nav = () => `<header><h1>Roster Planner</h1><nav><a href="#/rosters">Rosters</a><a href="#/employees">Employees</a><a href="#/locations">Locations</a><a href="#/availability">Availability</a><a href="#/rules">Shift rules</a><a href="#/settings">Settings</a></nav></header>`;
function layout(body) { app.innerHTML = `${nav()}<main>${toast ? notice(toast) : ''}${body}</main>`; }
function form(title, fields, action, submit = 'Save') { return `<section class="card"><h2>${title}</h2><form data-action="${action}">${fields}<button>${submit}</button></form></section>`; }
async function simpleList(kind, title, fields) { const rows = await list(kind); layout(`${form(`Add ${title}`, fields, `add-${kind}`)}<section class="card"><h2>${title}</h2>${rows.length ? `<ul>${rows.map(x => `<li>${x.name} <button data-delete="${kind}:${x.id}">Delete</button></li>`).join('')}</ul>` : '<p>No entries yet.</p>'}</section>`); }
async function viewRosters() { const rosters = await list('rosters'); layout(`${form('Create roster', '<label>Name <input name="name" required></label><label>Year <input name="year" type="number" value="2026" required></label><label>Month <input name="month" type="number" min="1" max="12" required></label><label>Target days worked <input name="target" type="number" value="20" required></label>', 'add-roster', 'Create roster')}<section class="card"><h2>Rosters</h2>${rosters.length ? rosters.map(r => `<article><a href="#/roster/${r.id}">${r.name} — ${r.year}-${String(r.month).padStart(2,'0')}</a><small>${r.productiveVersionId ? 'Productive version available' : 'No productive version'} · ${r.draftVersionId ? 'Proposal pending' : 'No proposal'}</small></article>`).join('') : '<p>Create your first monthly roster.</p>'}</section>`); }
async function viewAvailability() { const employees = await list('employees'), entries = await list('availabilities'); layout(`${form('Manual unavailable range', `<label>Employee <select name="employeeId">${employees.map(e => `<option value="${e.id}">${e.name}</option>`).join('')}</select></label><label>Start <input name="startDate" type="date" required></label><label>End <input name="endDate" type="date" required></label>`, 'add-availability')}<section class="card"><h2>Import availability JSON</h2><form data-action="import"><input name="file" type="file" accept="application/json,.json" required><button>Preview import</button></form>${preview ? previewHtml(preview) : ''}</section><section class="card"><h2>Recorded unavailability</h2><ul>${entries.map(e => `<li>${employees.find(x=>x.id===e.employeeId)?.name || 'Unknown'}: ${e.startDate}${e.endDate !== e.startDate ? ` to ${e.endDate}` : ''} <em>${e.source}</em> <button data-delete="availabilities:${e.id}">Delete</button></li>`).join('') || '<li>None</li>'}</ul></section>`); }
function previewHtml(p) { return `<div class="preview"><h3>Preview</h3><p>${p.matches.length === 1 ? `Matched ${p.matches[0].name}` : `Choose employee for “${p.employeeName}”`}</p>${p.matches.length !== 1 ? `<select id="import-employee">${p.matches.map(e=>`<option value="${e.id}">${e.name}</option>`).join('')}</select>` : ''}<p>${p.datesToAdd.length} dates to add; ${p.alreadyRecorded.length} already recorded.</p><button data-action="apply-import">Apply import</button></div>`; }
async function viewRoster(id) { const roster = await get('rosters', id); if (!roster) return layout(notice('Roster not found.')); const versions = await db.versionsFor(id); const p = roster.draftVersionId && await get('rosterVersions', roster.draftVersionId), prod = roster.productiveVersionId && await get('rosterVersions', roster.productiveVersionId); layout(`<section class="card"><a href="#/rosters">← Roster list</a><h2>${roster.name}</h2><p>${roster.year}-${String(roster.month).padStart(2,'0')}; target: ${roster.targetDaysWorked} days.</p><button data-generate="${id}">Generate whole-month proposal</button>${p ? ` <a class="button" href="#/proposal/${p.id}">Open proposal</a>` : ''}${prod ? ` <button data-copy="${id}">Create proposal from productive</button><h3>Productive (read-only)</h3>${grid(prod, true)}` : ''}</section>${versions.filter(v=>v.status==='archived').length ? `<section class="card"><h3>Archived versions</h3><p>${versions.filter(v=>v.status==='archived').length} preserved.</p></section>`:''}`); }
function grid(version, readonly = false) { const employees = window._employees || []; return `<div class="grid"><table><thead><tr><th>Date / Shift</th><th>Assignments</th><th>Status</th></tr></thead><tbody>${version.shifts.map(s => `<tr><td>${s.date}<br><strong>${s.name}</strong></td><td>${s.assignments.map(a=>{const e=employees.find(x=>x.id===a.employeeId); return `<span class="chip ${a.locked?'locked':''}">${e?.name||'Unknown'} ${a.locked?'🔒':''}${!readonly?` <button data-remove="${version.id}:${s.id}:${a.id}">×</button><button data-lock="${version.id}:${a.id}:${!a.locked}">${a.locked?'Unlock':'Lock'}</button>`:''}</span>`}).join(' ') || '—'}${!readonly?`<select data-add="${version.id}:${s.id}"><option value="">Add employee…</option>${employees.map(e=>`<option value="${e.id}">${e.name}</option>`).join('')}</select>`:''}</td><td>${s.assignments.length}/${s.minStaff} min, ${s.maxStaff} max</td></tr>`).join('')}</tbody></table></div>`; }
async function viewProposal(id) { const version = await get('rosterVersions', id); if (!version) return layout(notice('Proposal not found.')); const roster = await get('rosters', version.rosterId); window._employees = await list('employees'); const r = version.coverageReport; layout(`<section class="card"><a href="#/roster/${roster.id}">← ${roster.name}</a><h2>Editable proposal</h2><p>Generated from ${version.generatedFromDate}; seed ${version.generatorSeed}.</p><label>Regenerate from <input id="from-date" type="date" value="${version.generatedFromDate}"></label><button data-regenerate="${roster.id}">Regenerate</button><button data-accept="${version.id}">Review & accept</button>${grid(version)}</section><section class="card"><h3>Review</h3><p>Coverage gaps: ${r.unfilledSlots.length}; conflicts: ${r.conflicts.length}; target deviations: ${Object.values(r.targetDeviation).filter(Boolean).length}.</p><ul>${r.conflicts.map(c=>`<li>${c.message}</li>`).join('')}${r.unfilledSlots.map(g=>`<li>${g.date}: ${g.missing} unfilled slot(s)</li>`).join('') || '<li>No coverage gaps.</li>'}</ul></section>`); }
async function settings() { layout(`<section class="card"><h2>Backup</h2><button data-action="export">Download backup</button><form data-action="restore"><label>Replace all data from backup <input name="file" type="file" accept="application/json" required></label><button class="danger">Export safety backup & replace all data</button></form></section>`); }
async function route() { const [, kind, id] = location.hash.split('/'); try { if (kind === 'roster') await viewRoster(id); else if (kind === 'proposal') await viewProposal(id); else if (kind === 'employees') await simpleList('employees','Employees','<label>Name <input name="name" required></label><label>Location <select name="locationId"><option value="">Any location</option></select></label>'); else if (kind === 'locations') await simpleList('locations','Locations','<label>Name <input name="name" required></label>'); else if (kind === 'availability') await viewAvailability(); else if (kind === 'rules') await simpleList('shiftRules','Shift rules','<label>Name <input name="name" required></label><label>Min staff <input name="minStaff" type="number" min="1" value="1"></label><label>Max staff <input name="maxStaff" type="number" min="1" value="1"></label>'); else if (kind === 'settings') await settings(); else await viewRosters(); } catch(e) { layout(notice(e.message)); } }
function download(data, name) { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([JSON.stringify(data,null,2)], {type:'application/json'})); a.download = name; a.click(); URL.revokeObjectURL(a.href); }
document.addEventListener('submit', async e => { e.preventDefault(); const f=e.target, d=Object.fromEntries(new FormData(f)); try { if(f.dataset.action==='add-locations') await create('locations',{name:d.name}); else if(f.dataset.action==='add-employees') await create('employees',{name:d.name,locationId:d.locationId||null}); else if(f.dataset.action==='add-shiftRules') await create('shiftRules',{name:d.name,locationId:null,minStaff:+d.minStaff,maxStaff:+d.maxStaff,appliesOn:{type:'weekdays',weekdays:[0,1,2,3,4,5,6]}}); else if(f.dataset.action==='add-roster') await create('rosters',{name:d.name,year:+d.year,month:+d.month,targetDaysWorked:+d.target,daysWorkedTarget:{}}); else if(f.dataset.action==='add-availability') await create('availabilities',{employeeId:d.employeeId,startDate:d.startDate,endDate:d.endDate,status:'unavailable',source:'manual'}); else if(f.dataset.action==='import') { preview=makeImportPreview(await d.file.text(),await list('employees'),await list('availabilities')); } else if(f.dataset.action==='restore') { const safety=await exportBackup(); download(safety,'roster-planner-safety-backup.json'); if(confirm('Replace all current data?')) await replaceBackup(JSON.parse(await d.file.text())); } channel.postMessage('changed'); toast='Saved.'; await route(); } catch(err) { toast=err.message; await route(); } });
document.addEventListener('click', async e => { const el=e.target; try { if(el.dataset.delete){const [s,id]=el.dataset.delete.split(':');await remove(s,id)} else if(el.dataset.generate) await generateProposal(el.dataset.generate,await deps()); else if(el.dataset.copy) await copyProductiveToProposal(el.dataset.copy); else if(el.dataset.regenerate) await regenerateProposalFrom(el.dataset.regenerate,document.querySelector('#from-date').value,await deps()); else if(el.dataset.remove){const[v,shift,assignment]=el.dataset.remove.split(':');await editProposalAssignment(v,{type:'remove',shiftId:shift,assignmentId:assignment},await deps())} else if(el.dataset.lock){const[v,a,l]=el.dataset.lock.split(':');await setAssignmentLock(v,a,l==='true')} else if(el.dataset.accept){const v=await get('rosterVersions',el.dataset.accept);if(confirm(`Accept proposal with ${v.coverageReport.unfilledSlots.length} gaps and ${v.coverageReport.conflicts.length} conflicts?`))await acceptProposal(v.id,await deps())} else if(el.dataset.action==='apply-import'){const id=preview.employeeId||document.querySelector('#import-employee')?.value;if(!id)throw Error('Select an employee.');for(const entry of entriesForImport(preview,id))await save('availabilities',entry);preview=null} else if(el.dataset.action==='export')download(await exportBackup(),'roster-planner-backup.json'); else return; channel.postMessage('changed');toast='Saved.';await route(); } catch(err){toast=err.message;await route();} });
document.addEventListener('change', async e => { if(!e.target.dataset.add||!e.target.value)return; const [v,shift]=e.target.dataset.add.split(':'); try{await editProposalAssignment(v,{type:'add',shiftId:shift,employeeId:e.target.value},await deps());channel.postMessage('changed');toast='Assignment added.'}catch(err){toast=err.message}route(); });
addEventListener('hashchange', route); route();
